# Generated by Django 2.1 on 2018-08-02 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20180802_1041'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book_Instance',
            new_name='BookInstance',
        ),
    ]
